### ISSUE TITLE
aks-engine scale operation should consider current VMSS state into consideration

### ISSUE THREAD

**Issue by gurudattest** [Azure/aks-engine#2990] opened 2020-03-30 18:58 UTC
**Describe the request**
We recently had created clusters with aks-engine with VMSS as the agent pool and enabled automatic OS image upgrades. We've patched the generated template with the required changes like enabling auto os image upgrades and for that we need to setup a probe and setting the "enableautomaticupdates" to false as its a requirement.
          We wanted to manually scale up the instances. So, first we tried to scale up through portal/Az VMSS commands. The nodes were up but weren't showing up when we do "kubectl get nodes". Then we tried to use the aks-engine scale command and we got the below error

{
    "error": {
        "code": "BadRequest",
        "message": "windowsConfiguration.enableAutomaticUpdates cannot be set to true if upgradePolicy.automaticOSUpgradePolicy.enableAutomaticOSUpgrade is already true, starting from API version 2019-03-01"
    }
}

Although we patched the template by setting windowsConfiguration.enableAutomaticUpdates as false, it still complains that its true.  Its probably because we patched the template after the aks-engine had generated template. We had to take that route because we couldn't find any options to set VMSS health probe/ enableautomaticupdates options through kuberentes.json (https://github.com/Azure/aks-engine/blob/master/docs/topics/clusterdefinitions.md)

**Explain why AKS Engine needs it**
Scaling up VMSS is a very basic and common usecase. Once enabling auto os upgrade feature, this seems to be broken. Both of them are very essential functionalities and should be able to be working alongside each other. 

**Describe the solution you'd like**
aks-engine to consider the latest sate of VMSS (per the final ARM template/ any other updates done on the VMSS later on) when doing the scale operation.

**Describe alternatives you've considered**

**Additional context**

**Comment by jackfrancis** [comment] 2020-05-06 21:51
By design, `aks-engine scale` produces a new, updated ARM template representation of the target node pool. Thus, it will always update the VMSS model.

It is out of scope for `aks-engine scale` to be a thin wrapper around the VMSS API. If you wish to simply scale out your nodes after applying changes to the VMSS model, the VMSS API (CLI, portal) are the only ways to do so.

**Closed by jackfrancis** 2020-05-06 21:51 UTC
Labels: enhancement
