### ISSUE TITLE
docker-monitor doesn't start

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#2773] opened 2020-02-24 18:57 UTC
This is troubleshooting a containerd-backed node/vm, so perhaps this needs to be repro'd on a moby-backed node/vm, but it appears that the `docker-monitor` systemd service timer isn't doing anything:

```
azureuser@k8s-master-16867165-0:~$ sudo systemctl status docker-monitor
● docker-monitor.service - a script that checks docker health and restarts if needed
   Loaded: loaded (/etc/systemd/system/docker-monitor.service; static; vendor preset: enabled)
   Active: inactive (dead)
azureuser@k8s-master-16867165-0:~$ sudo cat /etc/systemd/system/docker-monitor.timer
[Unit]
Description=a timer that delays docker-monitor from starting too soon after boot
[Timer]
OnBootSec=30min
[Install]
WantedBy=multi-user.target
#EOF
azureuser@k8s-master-16867165-0:~$ uptime
 18:50:24 up 35 min,  1 user,  load average: 0.27, 0.30, 0.37
```

**Comment by mboersma** [comment] 2020-04-20 19:00
I couldn't reproduce with master and moby:

```
azureuser@k8s-master-26399701-0:~$ sudo systemctl status docker-monitor
● docker-monitor.service - a script that checks docker health and restarts if needed
   Loaded: loaded (/etc/systemd/system/docker-monitor.service; static; vendor preset: enabled)
   Active: active (running) since Mon 2020-04-20 18:56:38 UTC; 2min 21s ago
 Main PID: 25673 (bash)
    Tasks: 2 (limit: 9513)
   CGroup: /system.slice/docker-monitor.service
           ├─25673 bash /usr/local/bin/health-monitor.sh container-runtime
           └─27325 sleep 10

Apr 20 18:56:38 k8s-master-26399701-0 systemd[1]: Started a script that checks docker health and restarts if needed.
Apr 20 18:56:38 k8s-master-26399701-0 health-monitor.sh[25673]: Start kubernetes health monitoring for container-runtime
azureuser@k8s-master-26399701-0:~$ sudo uptime
 18:59:09 up 32 min,  1 user,  load average: 0.51, 0.60, 0.66
```

Will try containerd next.

**Comment by mboersma** [comment] 2020-04-20 21:45
Indeed it fails on a `containerd`-enabled cluster. This must be because the health-monitor.sh script expects to find either `docker` or `crictl` to check that everything is working, but the `moby-containerd` package has only `containerd` and `ctr`.

cc: @cpuguy83

**Comment by jackfrancis** [comment] 2020-04-20 21:46
Should we just remove these systemd jobs via CSE in a containerd config context?

**Comment by mboersma** [comment] 2020-04-20 21:53
Yeah, removing the `docker-monitor` units is an alternative, if there isn't a simple equivalent to `docker ps` using `ctr` or a supplemental package to install that provides `crictl`. I'm still poking around and I've asked cpuguy83 about that, but removing can be our fallback position.

**Comment by cpuguy83** [comment] 2020-04-20 21:57
There wouldn't be anything meaningful that `ctr` could do in the context of ensuring that the cri is functioning.
`crictl` would definitely be a better option in that regard.

**Comment by mboersma** [comment] 2020-04-20 22:01
I'll see if there's anything straightforward I can do using `crictl`; otherwise I'll disable this in the `{{if not NeedsContainerd}}` case.

**Comment by mboersma** [comment] 2020-04-21 16:35
Upon closer inspection, I don't think there's actually a problem here. The `docker-monitor.service` and `docker-monitor.timer` units are present on disk (they're part of the VHD), but the `systemctlEnableAndStart docker-monitor.timer` call that actually starts the service is already inside a `{{- if IsDockerContainerRuntime}}` block. So in the case of containerd, these systemd units are disabled (which is just as well because the script would fail, as noted above).

We could take the additional step of removing the units from disk in the case of containerd, but note that systemd has already parsed them and they're considered "loaded" but disabled, so more trickery might be required to completely purge all traces. I'd argue that's not worth it, but I'm open to any comments. (Otherwise, let's close this.)

**Closed** 2020-04-24 17:24 UTC
Labels: bug
