### ISSUE TITLE
VMExtensionProvisioningError when using the examples/coreos/kubernetes-coreos.json

### ISSUE THREAD

**Issue by dwhanger** [Azure/aks-engine#575] opened 2019-02-24 03:03 UTC
Issue: when running the examples/coreos/kubernetes-coreos.json with aks-engine, receive an error back "VMExtensionProvisioningError" with several screenfuls of information which I will paste below.
---

**What version of aks-engine?**:

---Version: v0.31.1

**Kubernetes version**:
1.10.11

**What happened**:

Received this error message back:

INFO[0022] Starting ARM Deployment (dwhanger-contoso-coreos-2142255026). This will take some time...
INFO[0524] Finished ARM Deployment (dwhanger-contoso-coreos-2142255026). Error: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details." Deta
ils=[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n
      \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'cse-agent-0'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=50\\n[stdout]\\n\\n[stderr]\\nt
imeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: fai
led to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run
command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc
': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such
file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or dir
ectory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\nti
meout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: fail
ed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run c
ommand 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc'
: No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such f
ile or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or dire
ctory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\n\\\
".\"\r\n      }\r\n    ]\r\n  }\r\n}"},{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n
   \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'cse-agent-1'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit stat
us=50\\n[stdout]\\n\\n[stderr]\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No suc
h file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or d
irectory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\n
timeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: fa
iled to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run
 command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'n
c': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such
 file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or di
rectory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\nt
imeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: fai
led to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run
command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc
': No such file or directory\\n\\\".\"\r\n      }\r\n    ]\r\n  }\r\n}"},{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal pr
ovisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'cse-master-0'. Error message: \\\"Enable failed: failed to execute command
: command terminated with exit status=50\\n[stdout]\\n\\n[stderr]\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout:
 failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to
run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command
 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No s
uch file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or
 directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\
\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout:
failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to r
un command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command
'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No su
ch file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or
directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\
ntimeout: failed to run command 'nc': No such file or directory\\n\\\".\"\r\n      }\r\n    ]\r\n  }\r\n}"}]
FATA[0525] Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details." Details=[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n
  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"messag
e\": \"VM has reported a failure when processing extension 'cse-agent-0'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=50\\n[stdout]\\n\\n[stderr]\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeo
ut: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed
to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run comm
and 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': N
o such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file
 or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directo
ry\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeou
t: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed t
o run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run comma
nd 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No
 such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file
or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or director
y\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\n\\\".\"\r\n      }\r\n    ]\r\n  }\r\n}"},{"code":"Conflict","message":"
{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvis
ioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'cse-agent-1'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=50\\n[stdout]\\n\\n[stderr]\\ntimeout: failed to run command 'nc':
 No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such fi
le or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or direc
tory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntime
out: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed
 to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run com
mand 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc':
No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such fil
e or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or direct
ory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeo
ut: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed
to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run comm
and 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\n\\\".\"\r\n      }\r\n    ]\r\n  }\r\n
}"},{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n
     \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'cse-master-0'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=50\\n[stdout]\\n\\n[stderr]\\nt
imeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: fai
led to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run
command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc
': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such
file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or dir
ectory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\nti
meout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: fail
ed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run c
ommand 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc'
: No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such f
ile or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or dire
ctory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\ntimeout: failed to run command 'nc': No such file or directory\\n\\\
".\"\r\n      }\r\n    ]\r\n  }\r\n}"}]

**What you expected to happen**:
no errors

**How to reproduce it** (as minimally and precisely as possible):
use the aks-engine to create an AKS cluster from the examples/coreos/kubernetes-coreos.json

**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment] 2019-02-26 21:03
Closing as this is a duplicate of #584 so we can keep the discussion in a single place. Thanks for reporting @dwhanger.

**Closed by CecileRobertMichon** 2019-02-26 21:03 UTC
