### ISSUE TITLE
SMTP configurations in kubernetes cluster 

### ISSUE THREAD

**Issue by nithinkumarsirigir** [Azure/aks-engine#2698] opened 2020-02-10 19:29 UTC
**Describe the issue**
cluster configured in my Azure Subscription and we had configured grafana 

we are traying to do mail configuration error messages saying that 

error messages : SMTP configuration error

**Comment by devigned** [comment] 2020-02-10 19:44
Can you provide more information that this? Perhaps, add some steps to reproduce.

The error message is extremely vague, and It's not clear to me where you are encountering the message. I'm afraid that in this state, this issue will have difficulty being resolved.

**Comment by nithinkumarsirigir** [comment] 2020-02-10 20:45
> Can you provide more information that this? Perhaps, add some steps to reproduce.
> 
> The error message is extremely vague, and It's not clear to me where you are encountering the message. I'm afraid that in this state, this issue will have difficulty being resolved.

![image](https://user-images.githubusercontent.com/33519642/74188410-5b4e5900-4c74-11ea-963d-019ca3ec3c14.png)

**Comment by devigned** [comment] 2020-02-10 21:06
How did you build the cluster? How did you setup the cluster? How did you setup Grafana?

Please reply with steps to reproduce this issue.

**Comment by nithinkumarsirigir** [comment] 2020-02-10 21:10
> How did you build the cluster? How did you setup the cluster? How did you setup Grafana?
> 
> Please reply with steps to reproduce this issue.

@sharan.vantipalli@gmail.com can you please elaborate devid's questions

**Comment by nithinkumarsirigir** [comment] 2020-02-10 21:12
By az cli we have build cluster with nodes of 2 and for that monitoring we have configured Helm services with grafana during that time notify alerts we have configuring SMTP services with help of yaml file

**Comment by devigned** [comment] 2020-02-10 21:20
I believe your Grafana deployment has not been configured with SMTP details. I think those are probably specified in your helm chart configuration: https://github.com/helm/charts/tree/master/stable/grafana#configuration.

I did a quick search engine query and came up with this document: https://community.grafana.com/t/smtp-not-configured-check-your-grafana-ini-config-files-smtp-section/1113. It looks like what you are running into.

I don't think this is something wrong with your cluster or how the cluster was built out via AKS-Engine, so I'm going to close the issue. If you feel that this is a problem with AKS-Engine, please feel free to reopen and specify your reasoning.

**Closed by devigned** 2020-02-10 21:20 UTC
Labels: azure-policy
