### ISSUE TITLE
Cluster auto scaler broken in system MSI enabled cluster if worker subnet is in different resource group

### ISSUE THREAD

**Issue by dennis-benzinger-hybris** [Azure/aks-engine#2373] opened 2019-11-27 09:38 UTC
In a cluster using system managed identities where the worker subnet is in a different resource group than the master VMs the cluster auto scaler doesn't work as the new worker VMs can't "join" the network properly.

The solution is to assign the role `Network Contributor` to all master identities on all vnets of worker subnets. This has to happen after the creation of the worker VMs but before the custom script extension for installing Kubernetes runs.

As the worker subnet (and in turn its vnet) is in a different RG the generated ARM template must create the role assignment in an embedded / nested / sub-template.

**Comment by devigned** [comment] 2019-11-27 16:44
Duplicate of https://github.com/Azure/aks-engine/issues/2367

**Closed** 2020-01-24 19:43 UTC
Labels: bug
