### ISSUE TITLE
Custom script is failing with new Aks-binary 

### ISSUE THREAD

**Issue by satishsudini** [Azure/aks-engine#1905] opened 2019-09-04 16:50 UTC
**Describe the bug**
Custom script is failing with new Aks-binary  

**Steps To Reproduce**

    "extensionProfiles": [
      {
          "name": "bootstrap",
          "version": "*",
          "extensionParameters": "*",
          "script": "script.sh",
          "urlQuery": "*"
      }
    ],

**Expected behavior**
CSE extension should be created without Error 

**AKS Engine version**
>0.36-0.40
working fine with < 0.32

**Kubernetes version**
1.15

**Additional context**
**output generated with aks binary v0.40 (which is having issue)**
          "dependsOn": [
        "[concat('Microsoft.Compute/virtualMachines/', variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')), '/extensions/cse', '-master-', copyIndex(variables('masterOffset')))]"
      ],
      "location": "[resourceGroup().location]",
      "name": "[concat(variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')), '/testcse', '-', 'master', '-', copyIndex(variables('masterOffset')))]",
      "properties": {},
      "type": "Microsoft.Compute/virtualMachines/extensions"
    },

**output generated with aks binary v0.31.3 (which is working fine)**
      "dependsOn": [
        "[concat('Microsoft.Compute/virtualMachines/', variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')), '/extensions/cse', '-master-', copyIndex(variables('masterOffset')))]"
      ],
      "location": "[resourceGroup().location]",
      "name": "[concat(variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')), '/testcse', '-', 'master', '-', copyIndex(variables('masterOffset')))]",
      "properties": {
        "autoUpgradeMinorVersion": true,
        "protectedSettings": {
          "storageAccountKey": "*",
          "storageAccountName": "*"
        },
        "publisher": "Microsoft.OSTCExtensions",
        "settings": {
          "commandToExecute": "[concat('/bin/bash -c \"/bin/bash ./bootstrap.sh ', parameters('bootstrapParameters'), ' >> /var/log/azure/bootstrap.log 2>&1 &\" &')]",
          "fileUris": [
            "*",
            "*",
            "*",
            "*"
          ]
        },
        "type": "CustomScriptForLinux",
        "typeHandlerVersion": "1.5"
      },
      "type": "Microsoft.Compute/virtualMachines/extensions"
    },

**Comment by CecileRobertMichon** [comment] 2019-09-04 16:54
This seems like a duplicate of https://github.com/Azure/aks-engine/issues/1751?

**Comment by jackfrancis** [comment] 2019-09-18 21:32
Duplicate of #1751

**Closed by jackfrancis** 2019-09-18 21:32 UTC
Labels: bug
