### ISSUE TITLE
AzureGov defaults regression

### ISSUE THREAD

**Issue by GreenCee** [Azure/aks-engine#786] opened 2019-03-18 15:38 UTC
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of aks-engine?**:
0.32+
---

**Kubernetes version**:
Default

**What happened**:
The master and workers fail with an error reported back:

In testing this is generated by the wrong distro being used as the default in Azure Government.

**What you expected to happen**:
Default distro for that environment to be Ubuntu and to successfully deploy

**How to reproduce it** (as minimally and precisely as possible):
Run aks-engine deploy against a minimal apimodel using --azure-env=AzureUSGovernmentCloud
(Example input apimodel.json)
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "",
      "vmSize": "Standard_D2_v2"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 3,
        "vmSize": "Standard_D2_v2",
        "availabilityProfile": "AvailabilitySet"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": ""
    }
  }
}

**Anything else we need to know**:
Ran deploy with arg --azure-env=AzureUSGovernmentCloud
It should default to the SovereignCloud distro: Ubuntu. Starting in version 0.32 it defaults to distro: aks which is not available in AzureUSGovernmentCloud

Workaround is to define distro manually as in #307 

Would be alternatively resolved by #645 

I'm looking into the code to see where the sovereign default distro conditionals are getting stomped or bypassed

Error message details:
Details=[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\":
\"VM has reported a failure when processing extension 'cse-agent-1'. Error message: \\\"Enable failed: failed to execute command: command terminated with
exit status=48\\\".\"\r\n      }\r\n    ]\r\n  }\r\n}"},{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'cse-agent-0'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=48\\\".\"\r\n      }\r\n    ]\r\n  }\r\n}"},{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'cse-master-0'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=48\\\".\"\r\n      }\r\n    ]\r\n  }\r\n}"},{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'cse-agent-2'. **Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=48**\\\".\"\r\n      }\r\n    ]\r\n  }\r\n}"}]

**Comment by zhiweiv** [comment] 2019-03-19 00:58
I got same error with 0.32.0, error 48 means `ERR_SYSTEMD_INSTALL_FAIL` per https://github.com/Azure/aks-engine/blob/master/parts/k8s/kubernetesprovisionsource.sh, I guess it was caused by #630. 0.31.3 works fine with AzureGov for me. Since #630 was reverted in 0.32.3, you can also try 0.32.3.

**Comment by CecileRobertMichon** [comment] 2019-03-19 19:14
This error was fixed in 0.32.3.

**Closed by CecileRobertMichon** 2019-03-19 19:14 UTC
