### ISSUE TITLE
Add `Standard_NC6_Promo` to list of GPU virtual machines

### ISSUE THREAD

**Issue by nicjac** [Azure/aks-engine#1203] opened 2019-05-02 12:47 UTC
**Is this a request for help?**:

No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Issue
---

**What version of aks-engine?**:
v0.35.0
---

**Kubernetes version**:
1.14.1

**What happened**:
When deploying a cluster with a node pool of size `Standard_NC6_Promo`, the Nvidia driver is not installed, and thus the GPU is not exposed as an available resource.

**What you expected to happen**:
GPU should be exposed as an available resource just like it is for regular `Standard_NC6` instances.

**How to reproduce it** (as minimally and precisely as possible):
Deploy a cluster with a `Standard_NC6_Promo` pool.

**Anything else we need to know**:

I was able to fix it locally. Here's the diff:

```
diff --git a/pkg/api/common/helper.go b/pkg/api/common/helper.go
index baa3811fc..4524ff40e 100644
--- a/pkg/api/common/helper.go
+++ b/pkg/api/common/helper.go
@@ -77,6 +77,7 @@ func IsNvidiaEnabledSKU(vmSize string) bool {
        dm := map[string]bool{
                // K80
                "Standard_NC6":   true,
+               "Standard_NC6_Promo":   true,
                "Standard_NC12":  true,
                "Standard_NC24":  true,
                "Standard_NC24r": true,
@@ -121,6 +122,10 @@ func GetNSeriesVMCasesForTesting() []struct {
                        "Standard_NC6",
                        true,
                },
+               {
+                       "Standard_NC6_Promo",
+                       true,
+               },
                {
                        "Standard_NC12",
                        true,
```

I can confirm that this works for me but wasn't sure if there was more to it, thus not submitting a patch at this stage. Please let me know if you would like me to do so?

Regards,
Nicolas

**Comment by CecileRobertMichon** [comment] 2019-05-02 17:01
Done in https://github.com/Azure/aks-engine/pull/1101

**Comment by ohthehugemanatee** [comment] 2019-05-02 17:27
Seems like the issue is actually that `_Promo` suffix should be ignored in `IsNvidiaEnabledSKU` regardless of what SKU it appears on, since it can appear on any SKU. 

Submitted a PR that ignores it and tests the ignore.

**Comment by ohthehugemanatee** [comment] 2019-05-02 17:31
... and someone else PR'ed it before I did. :|

Still, the merged PR adds `_Promo` types statically. I think my approach is better... @mboersma what do you think? Happy to make another PR for the minor change...

**Comment by CecileRobertMichon** [comment] 2019-05-02 17:58
#1101 added those VM the list but didn't actually fix this issue. I think you're PR is still relevant @ohthehugemanatee.

**Comment by CecileRobertMichon** [comment] 2019-05-02 18:01
closing in favor of #1209

**Closed by CecileRobertMichon** 2019-05-02 18:01 UTC
