### ISSUE TITLE
Aks engine deployment failed when we are using MSI with contributor access

### ISSUE THREAD

**Issue by amankohli** [Azure/aks-engine#4025] opened 2020-11-12 11:05 UTC
Below is the error:
The template deployment failed with error: 'Authorization failed for template resource xx of type 'Microsoft.Authorization/roleAssignments'. The client 'xxxxx' with object id 'xx' does not have permission to perform action 'Microsoft.Authorization/roleAssignments/write' at scope '/subscriptions/xxxxxxxx/resourceGroups/xxxxxxproviders/Microsoft.Authorization/roleAssignments/xxxx'.'.\\\"\\n\\\"\\r\\n\\r\\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot \

Steps To Reproduce
Below is the API Model:
```json
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "'$version'",
      "kubernetesConfig": {
        "useManagedIdentity": true,
        "userAssignedID": "/subscriptions/'$subscription'/resourceGroups/'$resourceGroup'/providers/Microsoft.ManagedIdentity/userAssignedIdentities/'$msiName'",
        "networkPlugin": "kubenet",
        "privateCluster": {
          "enabled": true
        }
      }
    },
    "masterProfile": {
      "count": 3,
      "dnsPrefix": "k8s'$environment'2dc",
      "vmSize": "Standard_D2s_v3",
      "OSDiskSizeGB": 100,
      "vnetSubnetId": "/subscriptions/'$subscription'/resourceGroups/'$resourceGroup'/providers/Microsoft.Network/virtualNetworks/'$vnetName'/subnets/'$subnetName'",
      "firstConsecutiveStaticIP": "'$ipRange'"
    },
    "agentPoolProfiles": [
      {
        "name": "node",
        "count": 9,
        "vmSize": "Standard_D8s_v3",
        "OSDiskSizeGB": 100,
        "vnetSubnetId": "/subscriptions/'$subscription'/resourceGroups/'$resourceGroup'/providers/Microsoft.Network/virtualNetworks/'$vnetName'/subnets/'$subnetName'"
      }
    ],
    "linuxProfile": {
      "adminUsername": "ubuntu",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "'$sshkey'"
          }
        ]
      }
    }
  }
}
```
Expected behavior
The template shouldn't error out and allow deployment with contributor access

AKS Engine version

v0.57.0
Kubernetes version
1.15

Additional context
Might be related to below bug:
https://github.com/Azure/aks-engine/issues/4014

**Comment by mgmm13** [comment] 2021-01-12 11:55
Bumping up this thread. Recently upgraded my aks-engine binary and as per checking, generated ARM template contains a roleAssignment object which is beyond scope of the Contributor role access.  

Since we are using a service principal with Contributor role, we are unable to create role assignments as part of ACL. Upon checking  [Microsoft documentation](https://docs.microsoft.com/en-us/azure/role-based-access-control/role-assignments-portal), creation of roleAssignment will need **User Access Administrator** or **Owner** role. 

Will the above roles  be needed moving forward, or is there a way to deploy without creation of RoleAssignments? 

AKS Engine version v0.58.0
Kubernetes version for deployment 1.20.0-rc.0

**Comment by matthieu-eck** [comment] 2021-04-26 07:59
Is there any workaround on this matter? We would like to avoid giving too much permissions to the service principal. Thanks!

_AKS Engine version v0.62.0
 Kubernetes version for deployment 1.21.0_

**Comment by devigned** [comment] 2021-04-26 11:02
The issue here is that the deploying identity, the service principal used to deploy the Azure Resource Manager template, needs to be able to create a managed identity and assign roles to that managed identity as part of building the cluster.

As stated above:
> Upon checking Microsoft documentation, creation of roleAssignment will need User Access Administrator or Owner role.

`[Contributor + User Access Administrator]` or `Owner` access is required to create and assign roles using an ARM template generated by AKS-Engine.

It could be possible to separate out the provisioning + role assignment of all identities used in the cluster, but that would take a pretty big refactor of the AKS-Engine ARM template generation, and would then require two separate deployments to have a working cluster. 
1) for provisioning the identities and roles (`Owner` or [[User Access Administrator](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#user-access-administrator) + [Managed Identity Contributor](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#managed-identity-contributor)] required)
2) for deploying the cluster using such a role (`Contributor` + [Managed Identity Operator](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#managed-identity-operator) required)

This would be a big change for AKS-Engine and one that we are unlikely to take on. If you are interested in this use case, I would suggest taking a look at [Cluster API Provider Azure](https://github.com/kubernetes-sigs/cluster-api-provider-azure).

**Comment by devigned** [comment] 2021-04-26 11:02
I'm going to close this issue as AKS-Engine is working as designed and we are unlikely to change this behavior in the future.

**Closed by devigned** 2021-04-26 11:02 UTC
Labels: bug
