### ISSUE TITLE
Old flannel installed by default

### ISSUE THREAD

**Issue by nirroz93** [Azure/aks-engine#3908] opened 2020-10-08 13:14 UTC
**Describe the bug**
Hi, I'm new to aks-engine (and azure) and I was surprised that after the installation basic aks-engine conf with flannel CNI I got by default an old flannel (v0.8.0 was released in July 2017 according to Flannel GitHub releases and 3 years is ancient history :-) ).  I know that I can override the image (and I will do it) - but opened a bug here so hopefully some1 will update it (I don't know if there is a reason for leaving it at 0.8.0). 

BTW, is there a policy for updating addons versions (each X time\releases?)?

**Expected behavior**
Default should be an up to date version of flannel.

**AKS Engine version**
latest (0.56.0)

**Kubernetes version**
1.19.0
**Additional context**

**Comment by jackfrancis** [comment] 2020-10-08 16:38
Hi @nirroz93, you are correct that the flannel addon implementation is old. No one is maintaining it (though we do test it to identify regressions, and in all cases thus far we've been able to keep it operational).

If you're new to AKS Engine have you considered the cluster-api + Azure solution?

- https://github.com/kubernetes-sigs/cluster-api-provider-azure
- https://cluster-api.sigs.k8s.io/user/quick-start.html

If you'd like to maintain your own flannel CNI spec, arguably the above is a better spot to do so. AKS Engine doesn't really create Kubernetes clusters that are easily modified after cluster creation time, and so you're sort of stuck with the concrete implementations provided (e.g., the specific, old flannel implementation).

cc @CecileRobertMichon @devigned

**Comment by jackfrancis** [comment] 2020-10-15 22:31
This is not a bug, so closing

**Closed by jackfrancis** 2020-10-15 22:31 UTC
Labels: bug
