### ISSUE TITLE
kubernetes upgrade with/without acs-engine

### ISSUE THREAD

**Issue by Mnbill** [Azure/aks-engine#736] opened 2019-03-06 14:09 UTC
Hello,

My kubernetes cluster (v1.10.1) and i want to upgrade it to (v1.10.11) or (v1.11.5).

In acs-engine documentation: "https://github.com/Azure/acs-engine/tree/master/examples/k8s-upgrade":

During the upgrade, acs-engine successively visits virtual machines that constitute the cluster (first the master nodes, then the agent nodes) and performs the following operations:
- cordon the node and drain existing workload
- delete the VM
- create new VM and install desired orchestrator version
- add the new VM to the cluster

It's possible to upgrade kubernetes version without deleting the VMs ?  How can we do that ?

It's possible to upgrade it without using acs-engine ?

NB: My disks are in th same azure ressource groupe of VMs.

ENVIRONMENT:
- Cloud Azure
- Cluster kubernetes v1.10.1 (1 Masterand 3 workers) was installed with acs-engine v0.13.0
- In the Master i have managed disks
- In the 3 workers i have unmanaged disks

/help
/help-wanted

Thanks,

**Comment by mboersma** [comment] 2019-03-11 19:08
> It's possible to upgrade kubernetes version without deleting the VMs ?

Not using `aks-engine`: the current strategy replaces nodes with new ones and isn't configurable. And I wouldn't recommend trying to upgrade manually because changes you make would not be reproducible (and if you do an `aks-engine scale` you'll get nodes of the original type).

**Comment by mboersma** [comment] 2019-03-13 16:53
@Mnbill it is possible to upgrade an acs-engine cluster using `aks-engine upgrade`. The name changed but the code didn't much.

However, this does do the destructive replacement of nodes (VMs) you wanted to avoid. And there are some border cases where upgrade won't work, so proceed with caution.

**Comment by Mnbill** [comment] 2019-03-14 10:25
Thank you @mboersma

**Comment by serbrech** [comment] 2019-03-14 13:36
Closing this issue.

**Closed by serbrech** 2019-03-14 13:36 UTC
Labels: feature/upgrade, help wanted, question
